sudo: required
services:
  - docker

before_install:
  - docker build -t axinalis/learning-kuber-test -f ./DockerfileTests .

script:
  - docker run axinalis/learning-kuber-test

after_success:
  - docker build -t axinalis/learning-kuber -f ./Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push axinalis/learning-kuber:latest