sudo: required
services:
  - docker

before_install:
  - curl https://registry-1.docker.io/v2/ && echo Works || echo Problem
  - docker build -t axinalis/learning-kuber-test -f ./DockerfileTests .

script:
  - docker run axinalis/learning-kuber-test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t axinalis/learning-kuber .
  - docker push axinalis/learning-kuber:latest

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: DockerAnKuber
  env: Dockerandkuber-env
  bucket_name: elasticbeanstalk-us-east-1-997496945967
  bucket_path: DockerAndKuber
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY