sudo: required
services:
  - docker

before_install:
  - docker build -t axinalis/learning-kuber-test -f ./DockerfileTests .

script:
  - docker run axinalis/learning-kuber-test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t axinalis/learning-kuber .
  - docker push axinalis/learning-kuber:latest