version: '2'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8081:8081"
    environment:
      DATASOURCE_URL: "jdbc:postgresql://database:5432/primes"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "fetu22AB"

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "fetu22AB"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "primes"
      PGPASSWORD: "fetu22AB"
      PGUSER: "postgres"
      PGDATABASE: "primes"