apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: database
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: "POSTGRES_USER"
              value: "postgres"
            - name: "POSTGRES_DB"
              value: "primes"
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD